config/routes.rb
Rails.application.routes.draw do

  resources :restorations
  resources :works
  resources :collections
  resources :warehouses
  resources :static_pages

  root "static_pages#index"
  devise_for :users, :controllers => {
      registrations: 'registrations'
  }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
    get 'index' => 'static_pages#index'
  end

  devise_scope :user do
    get 'sign_up', to: 'devise/registrations#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/collection.rb
class Collection < ApplicationRecord
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
    @warehouses = Warehouse.all
  end

  # GET /collections/1/edit
  def edit
    @warehouses = Warehouse.all
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    if Work.where(collection: @collection.name).count == 0
      @collection.destroy
      respond_to do |format|
        format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to collections_url, notice: 'No se eliminó la colección. Elimine obras relacionadas primero.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name, :description, :warehouse)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<div class="wrapper">
  <%= form_with(model: collection, local: true, :html => {:class => 'form-signin'}) do |form| %>
      <% if collection.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

            <ul>
              <% collection.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="form-group">
        <%= form.label :nombre %>
        <%= form.text_field :name, id: :collection_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :descripción %>
        <%= form.text_field :description, id: :collection_description, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :almacén %>
        <% options = options_from_collection_for_select(@warehouses, 'name', 'name') %>
        <%= form.select :warehouse,  options,  {}, :class => 'form-control selectpicker', 'data-live-search' => 'true' %>
      </div>
      <div class="actions">
        <%= form.submit "Guardar", class: "btn btn-primary center-block"%>
      </div>
  <% end %>

  <%= link_to 'Regresar a Colección' .html_safe, @collection, class: "return text-center center-block" %>
</div>

app/views/collections/edit.html.erb
<div class="container text-center">
  <h1 id="mainview">EDITAR COLECCIÓN</h1>
</div>

<%= render 'form', collection: @collection %>

app/views/collections/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1 id="mainview">VISTA GENERAL - COLECCIONES
    <%= link_to '<i class="glyphicon glyphicon-plus-sign"></i>'.html_safe, new_collection_path %>
  </h1>
</div>

<div class="container">
  <table id = "collections" class="table table-bordered table-striped table-hover table-responsive">
    <thead>
    <tr>
      <th>ID</th>
      <th>Almacén</th>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Total de Obras</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @collections.each do |collection| %>
        <tr>
          <td><%= collection.id %></td>
          <td><%= collection.warehouse %></td>
          <td><%= collection.name %></td>
          <td><%= collection.description %></td>
          <td><%= Work.where(collection: collection.name).count %></td>
          <td>
            <%= link_to '<i class="glyphicon glyphicon-eye-open"></i>'.html_safe, collection%>

            <%= link_to '<i class="glyphicon glyphicon-edit"></i>'.html_safe, edit_collection_path(collection) %>

            <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, collection, method: :delete, data: { confirm: '¿Desea eliminar la colección?' }  %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<script>
    $( document).ready(function() {
        $('#collections').DataTable();
    } );
</script>

app/views/collections/new.html.erb
<div class="container text-center">
  <h1 id="mainview">NUEVA COLECCIÓN</h1>
</div>

<%= render 'form', collection: @collection %>

app/views/collections/show.html.erb
<div class="container">
  <div class="text-left">
    <h1 id="mainview"><%= @collection.name %>
    </h1>
  </div>
</div>

<div class="container">
  <table class="table table-bordered table-striped table-hover table-responsive">
    <thead>
    <tr>
      <th>
        <div class="row">
          <div class="col-lg-6">
            <div class="col-md-4">
              <div class="show-title">Almacén:</div>
            </div>
            <div class="col-md-8">
              <div class="show-content"><%= @collection.warehouse%></div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="col-md-4">
              <div class="show-title">Total de Obras:</div>
            </div>
            <div class="col-md-8">
              <div class="show-content">
                <%= Work.where(collection: @collection.name).count %>
              </div>
            </div>
          </div>
        </div>
        <div class="row row-margin-top">
          <div class="col-lg-6">
            <div class="col-md-4">
              <div class="show-title">Descripción:</div>
            </div>
            <div class="col-md-8">
              <div class="show-content"><%= @collection.description %></div>
            </div>
          </div>
          <div class="col-lg-6">
          </div>
        </div>
        <div class="row row-margin-top-buttons">
          <div class="text-center">
            <%= link_to '<button type="button" class="btn btn-success">Editar</button>' .html_safe, edit_collection_path(@collection) %>
            <%= link_to '<button type="button" class="btn btn-danger">Eliminar</button>' .html_safe, @collection, method: :delete, data: { confirm: '¿Desea eliminar la colección?' } %>
          </div>
        </div>
      </th>
    </tr>
    </thead>
  </table>
</div>
<%= link_to 'Regresar a Colecciones' .html_safe, collections_path, class: "return text-center center-block" %>