config/routes.rb
Rails.application.routes.draw do

  resources :restorations
  resources :works
  resources :collections
  resources :warehouses
  resources :static_pages

  root "static_pages#index"
  devise_for :users, :controllers => {
      registrations: 'registrations'
  }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
    get 'index' => 'static_pages#index'
  end

  devise_scope :user do
    get 'sign_up', to: 'devise/registrations#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restoration.rb
class Restoration < ApplicationRecord
end

app/controllers/restorations_controller.rb
class RestorationsController < ApplicationController
  before_action :set_restoration, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /restorations
  # GET /restorations.json
  def index
    @restorations = Restoration.all
  end

  # GET /restorations/1
  # GET /restorations/1.json
  def show
  end

  # GET /restorations/new
  def new
    @restoration = Restoration.new
    @works = Work.all
  end

  # GET /restorations/1/edit
  def edit
    @works = Work.all
  end

  # POST /restorations
  # POST /restorations.json
  def create
    @restoration = Restoration.new(restoration_params)

    respond_to do |format|
      if @restoration.save
        format.html { redirect_to @restoration, notice: 'Restoration was successfully created.' }
        format.json { render :show, status: :created, location: @restoration }
      else
        format.html { render :new }
        format.json { render json: @restoration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restorations/1
  # PATCH/PUT /restorations/1.json
  def update
    respond_to do |format|
      if @restoration.update(restoration_params)
        format.html { redirect_to @restoration, notice: 'Restoration was successfully updated.' }
        format.json { render :show, status: :ok, location: @restoration }
      else
        format.html { render :edit }
        format.json { render json: @restoration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restorations/1
  # DELETE /restorations/1.json
  def destroy
    @restoration.destroy
    respond_to do |format|
      format.html { redirect_to restorations_url, notice: 'Restoration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restoration
      @restoration = Restoration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restoration_params
      params.require(:restoration).permit(:reason, :responsible, :since,
                                          :until, :work)
    end
end

app/helpers/restorations_helper.rb
module RestorationsHelper
end

app/views/restorations/_form.html.erb
<div class="wrapper">
  <%= form_with(model: restoration, local: true, :html => {:class => 'form-signin'}) do |form| %>
      <% if restoration.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(restoration.errors.count, "error") %> prohibited this restoration from being saved:</h2>

            <ul>
              <% restoration.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="form-group">
        <div class="form-group">
          <%= form.label :obra %>
          <% options = options_from_collection_for_select(@works, 'name', 'name') %>
          <%= form.select :work,  options,  {}, :class => 'form-control selectpicker', 'data-live-search' => 'true' %>
        </div>
      </div>
      <div class="form-group">
        <%= form.label :razón %>
        <%= form.text_field :reason, id: :restoration_reason, class: "form-control"%>
      </div>
      <div class="form-group">
        <%= form.label :responsable %>
        <%= form.text_field :responsible, id: :restoration_responsible, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :desde %>
        <%= form.date_field :since, id: :restoration_since, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :hasta %>
        <%= form.date_field :until, id: :restoration_until, class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit "Guardar", class: "btn btn-primary center-block"%>
      </div>
  <% end %>

  <%= link_to 'Regresar a Restauración' .html_safe, @restoration, class: "return text-center center-block" %>
</div>

app/views/restorations/edit.html.erb
<div class="container text-center">
  <h1 id="mainview">EDITAR RESTAURACIÓN</h1>
</div>

<%= render 'form', restoration: @restoration %>

app/views/restorations/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1 id="mainview">VISTA GENERAL - RESTAURACIONES
    <%= link_to '<i class="glyphicon glyphicon-plus-sign"></i>'.html_safe, new_restoration_path%>
  </h1>
</div>

<div class="container">
  <table id= "restorations" class="table table-bordered table-striped table-hover table-responsive">
    <thead>
    <tr>
      <th>ID</th>
      <th>Obra</th>
      <th>Razón</th>
      <th>Responsable</th>
      <th>Desde</th>
      <th>Hasta</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @restorations.each do |restoration| %>
        <tr>
          <td><%= restoration.id %></td>
          <td><%= restoration.work %></td>
          <td><%= restoration.reason %></td>
          <td><%= restoration.responsible %></td>
          <td><%= restoration.since %></td>
          <td><%= restoration.until %></td>
          <td>
            <%= link_to '<i class="glyphicon glyphicon-eye-open"></i>'.html_safe, restoration%>

            <%= link_to '<i class="glyphicon glyphicon-edit"></i>'.html_safe, edit_restoration_path(restoration) %>

            <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, restoration, method: :delete, data: { confirm: '¿Desea eliminar la restauración?' }  %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<script>

    $( document).ready(function() {
        $('#restorations').DataTable();
    } );
</script>

app/views/restorations/new.html.erb
<div class="container text-center">
  <h1 id="mainview">NUEVA RESTAURACIÓN</h1>
</div>

<%= render 'form', restoration: @restoration %>

app/views/restorations/show.html.erb
<div class="container">
  <div class="text-left">
    <h1 id="mainview">#<%= @restoration.id %> "<%= @restoration.work %>"
    </h1>
  </div>
</div>

<div class="container">
  <table class="table table-bordered table-striped table-hover table-responsive">
    <thead>
    <tr>
      <th>
        <div class="row">
          <div class="col-lg-6">
            <div class="col-md-5">
              <div class="show-title">Responsable</div>
            </div>
            <div class="col-md-7">
              <div class="show-content">"<%= @restoration.responsible %>"</div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="col-md-5">
              <div class="show-title">Desde:</div>
            </div>
            <div class="col-md-7">
              <div class="show-content"><%= @restoration.since.to_date.to_formatted_s(:rfc822)%></div>
            </div>
          </div>
        </div>
        <div class="row row-margin-top">
          <div class="col-lg-6">
            <div class="col-md-5">
              <div class="show-title">Motivo:</div>
            </div>
            <div class="col-md-7">
              <div class="show-content"><%= @restoration.reason %></div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="col-md-5">
              <div class="show-title">Hasta:</div>
            </div>
            <div class="col-md-7">
              <div class="show-content"><%= @restoration.until.to_date.to_formatted_s(:rfc822)%></div>
            </div>
          </div>
        </div>
        <div class="row row-margin-top-buttons">
          <div class="text-center">
            <%= link_to '<button type="button" class="btn btn-success">Editar</button>' .html_safe, edit_restoration_path(@restoration) %>
            <%= link_to '<button type="button" class="btn btn-danger">Eliminar</button>' .html_safe, @restoration, method: :delete, data: { confirm: '¿Desea eliminar la restauración?' } %>
          </div>
        </div>
      </th>
    </tr>
    </thead>
  </table>
</div>
<%= link_to 'Regresar a Restauraciones' .html_safe, restorations_path, class: "return text-center center-block" %>