config/routes.rb
Rails.application.routes.draw do

  resources :restorations
  resources :works
  resources :collections
  resources :warehouses
  resources :static_pages

  root "static_pages#index"
  devise_for :users, :controllers => {
      registrations: 'registrations'
  }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
    get 'index' => 'static_pages#index'
  end

  devise_scope :user do
    get 'sign_up', to: 'devise/registrations#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/work.rb
class Work < ApplicationRecord
  mount_uploader :certificate_picture, PictureUploader

  STATUS_LIST = ["Buen estado", "Deterioro natural", "Deterioro controlado",
                 "Delicada", "Completamente deteriorada", "Estado crítico"]
  SITUATION_LIST = ["En exposición", "En resguardo",
                    "En préstamo", "En restauración"]
  ORIGIN_LIST = ["Compra", "Donación", "Comodato"]
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
    @warehouses = Warehouse.all
    @collections = Collection.all
  end

  # GET /works/1/edit
  def edit
    @warehouses = Warehouse.all
    @collections = Collection.all
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    if Restoration.where(work: @work.name).count == 0
      @work.destroy
      respond_to do |format|
        format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to works_url, notice: 'No se eliminó la obra. Elimine restauraciones relacionadas primero.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:name, :author, :dimensions,
                                   :technique, :year, :location, :status,
                                   :situation, :situation_since, :situation_until,
                                   :owner, :origin, :has_certificate,
                                   :certificate_picture, :certified_by, :value,
                                   :valuer, :collection, :warehouse)
    end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<div class="wrapper">
  <%= form_with(model: work, local: true) do |form| %>
      <% if work.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(work.errors.count, "error") %> prohibited this work from being saved:</h2>

            <ul>
              <% work.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="container">
        <table class="table table-bordered table-striped table-hover table-responsive">
          <thead>
          <tr>
            <th>
              <div class="row">
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :nombre %>
                    <%= form.text_field :name, id: :work_name, class: "form-control" %>
                  </div>
                </div>
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :situación %>
                    <%= form.select :situation,  Work::SITUATION_LIST,  {}, :class => 'form-control selectpicker', 'data-live-search' => 'true' %>
                  </div>
                </div>
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :desde %>
                    <%= form.date_field :situation_since, id: :work_situation_since, class: "form-control" %>
                  </div>
                </div>
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :hasta %>
                    <%= form.date_field :situation_until, id: :work_situation_until, class: "form-control" %>
                  </div>
                </div>
              </div>
              <div class="row row-margin-top">
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :autor %>
                    <%= form.text_field :author, id: :work_author, class: "form-control" %>
                  </div>
                </div>
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :collección %>
                    <% options = options_from_collection_for_select(@collections, 'name', 'name') %>
                    <%= form.select :collection,  options,  {}, :class => 'form-control selectpicker', 'data-live-search' => 'true' %>
                  </div>
                </div>
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :estado %>
                    <%= form.select :status, Work::STATUS_LIST,  {}, :class => 'form-control selectpicker', 'data-live-search' => 'true' %>
                  </div>
                </div>
              </div>
              <div class="row row-margin-top">
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :técnica %>
                    <%= form.text_field :technique, id: :work_technique, class: "form-control" %>
                  </div>
                </div>
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :dimensiones %>
                    <%= form.text_field :dimensions, id: :work_dimensions, class: "form-control"%>
                  </div>
                </div>
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :año %>
                    <%= form.text_field :year, id: :work_year, class: "form-control" %>
                  </div>
                </div>
              </div>
              <div class="row row-margin-top">
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :origen %>
                    <%= form.select :origin,  Work::ORIGIN_LIST,  {}, :class => 'form-control selectpicker', 'data-live-search' => 'true' %>
                  </div>
                </div>
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :ubicación %>
                    <%= form.text_field :location, id: :work_location, class: "form-control" %>
                  </div>
                </div>
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :dueño %>
                    <%= form.text_field :owner, id: :work_owner, class: "form-control" %>
                  </div>
                </div>
              </div>
              <div class="row row-margin-top">
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :valor %>
                    <%= form.text_field :value, id: :work_value, class: "form-control" %>
                  </div>
                </div>
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :valuador %>
                    <%= form.text_field :valuer, id: :work_valuer, class: "form-control" %>
                  </div>
                </div>
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :tiene_certificado %>
                    <%= form.check_box :has_certificate, id: :work_has_certificate, class: "form-check-input" %>
                    <%= form.file_field :certificate_picture, id: :work_certificate_picture, class: "form-control" %>
                  </div>
                </div>
              </div>
              <div class="row row-margin-top">
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :almacén %>
                    <% options = options_from_collection_for_select(@warehouses, 'name', 'name') %>
                    <%= form.select :warehouse,  options,  {}, :class => 'form-control selectpicker', 'data-live-search' => 'true' %>
                  </div>
                </div>
                <div class="col-lg-3">
                  <div class="form-group">
                    <%= form.label :certificador, id: :label_certified_by%>
                    <%= form.text_field :certified_by, id: :work_certified_by, class: "form-control" %>
                  </div>
                </div>
              </div>
            </th>
          </tr>
          </thead>
        </table>
      </div>
      <div class="actions">
        <%= form.submit "Guardar", class: "btn btn-primary center-block"%>
      </div>
    <% end %>
  <%= link_to 'Regresar a Obra' .html_safe, @work, class: "return text-center center-block" %>
</div>

app/views/works/edit.html.erb
<div class="container text-center">
  <h1 id="mainview">EDITAR OBRA</h1>
</div>

<%= render 'form', work: @work %>

app/views/works/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1 id="mainview">VISTA GENERAL - OBRAS
    <%= link_to '<i class="glyphicon glyphicon-plus-sign"></i>'.html_safe, new_work_path %>
    <%= link_to '<i class="glyphicon glyphicon-save"></i>'.html_safe, new_work_path %>
  </h1>
</div>

<div class="container">
  <table id="works" class="table table-bordered table-striped table-hover table-responsive">
    <thead>
    <tr>
      <th>ID</th>
      <th>Título</th>
      <th>Autor</th>
      <th>Año</th>
      <th>Detalles</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
      <% @works.each do |work| %>
        <tr>
          <td><%= work.id %></td>
          <td><%= work.name %></td>
          <td><%= work.author %></td>
          <td><%= work.year %></td>
          <td><%= link_to 'Ver detalles', work %></td>
          <td>
            <%= link_to '<i class="glyphicon glyphicon-edit"></i>'.html_safe, edit_work_path(work) %>

            <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, work, method: :delete, data: { confirm: '¿Desea eliminar la obra?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<script>
    $( document).ready(function() {
        $('#works').DataTable();
    } );
</script>

app/views/works/new.html.erb
<div class="container text-center">
  <h1 id="mainview">NUEVA OBRA</h1>
</div>

<%= render 'form', work: @work %>

app/views/works/show.html.erb
<div class="container">
  <div class="text-left">
    <h1 id="mainview">"<%= @work.name %>"</h1>
  </div>
</div>

<div class="container">
  <table class="table table-bordered table-striped table-hover table-responsive">
    <thead>
      <tr>
        <th>
          <div class="row">
            <div class="col-lg-3">
              <div class="col-md-4">
                <div class="show-title">Título:</div>
              </div>
              <div class="col-md-8">
                <div class="show-content">"<%= @work.name %>"</div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="col-md-5">
                <div class="show-title">Situación:</div>
              </div>
              <div class="col-md-7">
                <div class="show-content"><%= @work.situation %></div>
              </div>
            </div>
            <div class="col-lg-5">
              <div class="col-md-2">
                <div class="show-title">Desde:</div>
              </div>
              <div class="col-md-4">
                <div class="show-content"><%= @work.situation_since.to_date.to_formatted_s(:rfc822)  %></div>
              </div>
              <div class="col-md-2">
                <div class="show-title">Hasta:</div>
              </div>
              <div class="col-md-4">
                <div class="show-content"><%= @work.situation_until.to_date.to_formatted_s(:rfc822) %></div>
              </div>
            </div>
          </div>
          <div class="row row-margin-top">
            <div class="col-lg-3">
              <div class="col-md-4">
                <div class="show-title">Autor:</div>
              </div>
              <div class="col-md-8">
                <div class="show-content"><%= @work.author %></div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="col-md-5">
                <div class="show-title">Colección:</div>
              </div>
              <div class="col-md-7">
                <div class="show-content"><%= @work.collection %></div>
              </div>
            </div>
            <div class="col-lg-5">
              <div class="col-md-2">
                <div class="show-title">Estado:</div>
              </div>
              <div class="col-md-10">
                <div class="show-content"><%= @work.status %></div>
              </div>
            </div>
          </div>
          <div class="row row-margin-top">
            <div class="col-lg-3">
              <div class="col-md-4">
                <div class="show-title">Técnica:</div>
              </div>
              <div class="col-md-8">
                <div class="show-content"><%= @work.technique %></div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="col-md-5">
                <div class="show-title">Dimensiones:</div>
              </div>
              <div class="col-md-7">
                <div class="show-content"><%= @work.dimensions %></div>
              </div>
            </div>
            <div class="col-lg-5">
              <div class="col-md-2">
                <div class="show-title">Año:</div>
              </div>
              <div class="col-md-10">
                <div class="show-content"><%= @work.year %></div>
              </div>
            </div>
          </div>
          <div class="row row-margin-top">
            <div class="col-lg-3">
              <div class="col-md-4">
                <div class="show-title">Origen:</div>
              </div>
              <div class="col-md-8">
                <div class="show-content"><%= @work.origin %></div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="col-md-5">
                <div class="show-title">Ubicación:</div>
              </div>
              <div class="col-md-7">
                <div class="show-content"><%= @work.location %></div>
              </div>
            </div>
            <div class="col-lg-5">
              <div class="col-md-2">
                <div class="show-title">Dueño:</div>
              </div>
              <div class="col-md-10">
                <div class="show-content"><%= @work.owner %></div>
              </div>
            </div>
          </div>
          <div class="row row-margin-top">
            <div class="col-lg-3">
              <div class="col-md-4">
                <div class="show-title">Valor:</div>
              </div>
              <div class="col-md-8">
                <div class="show-content"><%= @work.value %></div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="col-md-5">
                <div class="show-title">Valuador:</div>
              </div>
              <div class="col-md-7">
                <div class="show-content"><%= @work.valuer %></div>
              </div>
            </div>
            <div class="col-lg-4"></div>
          </div>
          <div class="row row-margin-top">
            <div class="col-lg-3">
              <div class="col-md-4">
                <div class="show-title">Almacén:</div>
              </div>
              <div class="col-md-8">
                <div class="show-content"><%= @work.warehouse %></div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="col-md-5">
                <% if @work.has_certificate? %>
                    <div class="show-title">Certificador:</div>
                <% end %>
              </div>
              <div class="col-md-7">
                <% if @work.has_certificate? %>
                    <div class="show-content"><%= @work.certified_by %></div>
                <% end %>
              </div>
            </div>
            <div class="col-lg-5">
              <div class="col-md-12">
                <% if @work.has_certificate? %>
                    <div class="show-content">
                      <%= link_to 'Ver Certificado', @work.certificate_picture_url %>
                    </div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="row row-margin-top-buttons">
            <div class="text-center">
              <%= link_to '<button type="button" class="btn btn-success">Editar</button>' .html_safe, edit_work_path(@work) %>
              <%= link_to '<button type="button" class="btn btn-danger">Eliminar</button>' .html_safe, @work, method: :delete, data: { confirm: '¿Desea eliminar la obra?' } %>
            </div>
          </div>
        </th>
      </tr>
      </thead>
  </table>
</div>

<%= link_to 'Regresar a Obras' .html_safe, works_path, class: "return text-center center-block" %>