config/routes.rb
Rails.application.routes.draw do

  resources :restorations
  resources :works
  resources :collections
  resources :warehouses
  resources :static_pages

  root "static_pages#index"
  devise_for :users, :controllers => {
      registrations: 'registrations'
  }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
    get 'index' => 'static_pages#index'
  end

  devise_scope :user do
    get 'sign_up', to: 'devise/registrations#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /warehouses
  # GET /warehouses.json
  def index
    @warehouses = Warehouse.all
  end

  # GET /warehouses/1
  # GET /warehouses/1.json
  def show
  end

  # GET /warehouses/new
  def new
    @warehouse = Warehouse.new
  end

  # GET /warehouses/1/edit
  def edit
  end

  # POST /warehouses
  # POST /warehouses.json
  def create
    @warehouse = Warehouse.new(warehouse_params)

    respond_to do |format|
      if @warehouse.save
        format.html { redirect_to @warehouse, notice: 'Warehouse was successfully created.' }
        format.json { render :show, status: :created, location: @warehouse }
      else
        format.html { render :new }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warehouses/1
  # PATCH/PUT /warehouses/1.json
  def update
    respond_to do |format|
      if @warehouse.update(warehouse_params)
        format.html { redirect_to @warehouse, notice: 'Warehouse was successfully updated.' }
        format.json { render :show, status: :ok, location: @warehouse }
      else
        format.html { render :edit }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warehouses/1
  # DELETE /warehouses/1.json
  def destroy
    if Work.where(warehouse: @warehouse.name).count == 0 && Collection.where(warehouse: @warehouse.name).count == 0
      @warehouse.destroy
      respond_to do |format|
        format.html { redirect_to warehouses_url, notice: 'Warehouse was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to warehouses_url, notice: 'No se eliminó el almacén. Elimine obras y colecciones relacionadas primero.' }

      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warehouse
      @warehouse = Warehouse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def warehouse_params
      params.require(:warehouse).permit(:name, :location, :description)
    end
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/warehouses/_form.html.erb
<div class="wrapper">
  <%= form_with(model: warehouse, local: true, :html => {:class => 'form-signin'}) do |form| %>
      <% if warehouse.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(warehouse.errors.count, "error") %> prohibited this warehouse from being saved:</h2>

            <ul>
              <% warehouse.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="form-group">
        <%= form.label :nombre %>
        <%= form.text_field :name, id: :warehouse_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :descripción %>
        <%= form.text_field :description, id: :warehouse_description, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :ubicación %>
        <%= form.text_field :location, id: :warehouse_location, :class => 'form-control' %>
      </div>
      <div class="actions">
        <%= form.submit "Guardar", class: "btn btn-primary center-block"%>
      </div>
  <% end %>
  <%= link_to 'Regresar a Almacén' .html_safe, @warehouse, class: "return text-center center-block" %>
</div>

app/views/warehouses/edit.html.erb
<div class="container text-center">
  <h1 id="mainview">EDITAR ALMACÉN</h1>
</div>

<%= render 'form', warehouse: @warehouse %>

app/views/warehouses/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1 id="mainview">VISTA GENERAL - ALMACENES
    <%= link_to '<i class="glyphicon glyphicon-plus-sign"></i>'.html_safe, new_warehouse_path%>
  </h1>
</div>

<div class="container">
  <table id="warehouses" class="table table-bordered table-striped table-hover table-responsive">
    <thead>
    <tr>
      <th>ID</th>
      <th>Almacén</th>
      <th>Ubicación</th>
      <th>Descripción</th>
      <th>Total de Colecciones</th>
      <th>Total de Obras</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @warehouses.each do |warehouse| %>
        <tr>
          <td><%= warehouse.id %></td>
          <td><%= warehouse.name %></td>
          <td><%= warehouse.location %></td>
          <td><%= warehouse.description %></td>
          <td><%= Collection.where(warehouse: warehouse.name).count %></td>
          <td><%= Work.where(warehouse: warehouse.name).count %></td>
          <td>
            <%= link_to '<i class="glyphicon glyphicon-eye-open"></i>'.html_safe, warehouse%>

            <%= link_to '<i class="glyphicon glyphicon-edit"></i>'.html_safe, edit_warehouse_path(warehouse) %>

            <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, warehouse, method: :delete, data: { confirm: '¿Desea eliminar el almacén?' }  %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<script>
    $( document).ready(function() {
        $('#warehouses').DataTable();
    } );
</script>

app/views/warehouses/new.html.erb
<div class="container text-center">
  <h1 id="mainview">NUEVO ALMACÉN</h1>
</div>

<%= render 'form', warehouse: @warehouse %>

app/views/warehouses/show.html.erb
<div class="container">
  <div class="text-left">
    <h1 id="mainview"><%= @warehouse.name %>
    </h1>
  </div>
</div>

<div class="container">
  <table class="table table-bordered table-striped table-hover table-responsive">
    <thead>
    <tr>
      <th>
        <div class="row">
          <div class="col-lg-6">
            <div class="col-md-5">
              <div class="show-title">Ubicación:</div>
            </div>
            <div class="col-md-7">
              <div class="show-content"><%= @warehouse.location %></div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="col-md-7">
              <div class="show-title">Total de Colecciones:</div>
            </div>
            <div class="col-md-5">
              <div class="show-content">
                <%= Collection.where(warehouse: @warehouse.name).count %>
              </div>
            </div>
          </div>
        </div>
        <div class="row row-margin-top">
          <div class="col-lg-6">
            <div class="col-md-5">
              <div class="show-title">Descripción:</div>
            </div>
            <div class="col-md-7">
              <div class="show-content"><%= @warehouse.description %></div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="col-md-7">
              <div class="show-title">Total de Obras:</div>
            </div>
            <div class="col-md-5">
              <div class="show-content">
                <%= Work.where(warehouse: @warehouse.name).count %>
              </div>
            </div>
          </div>
        </div>
        <div class="row row-margin-top-buttons">
          <div class="text-center">
            <%= link_to '<button type="button" class="btn btn-success">Editar</button>' .html_safe, edit_warehouse_path(@warehouse) %>
            <%= link_to '<button type="button" class="btn btn-danger">Eliminar</button>' .html_safe, @warehouse, method: :delete, data: { confirm: '¿Desea eliminar el almacén?' } %>
          </div>
        </div>
      </th>
    </tr>
    </thead>
  </table>
</div>
<%= link_to 'Regresar a Almacenes' .html_safe, warehouses_path, class: "return text-center center-block" %>